//! Card data table.
//!
//! Pure data only — no behavior. The 577 concrete CardModel subclasses in
//! the StS2 decompile are reduced to a flat list of `CardData` records and
//! loaded from `data/cards.json` (regenerated by `cargo run -p extract-cards`).
//!
//! Card *behavior* (`OnPlay`, multi-card interactions, status-effect resolution)
//! lives in a later port. This module is the foundation for:
//!   - Phase 1 observation encoding (card → feature vector)
//!   - Combat-state replay (need ids + costs + targets)
//!   - Strategic-decision generation (deck composition stats)
//!
//! Enum names match the C# decompile except where they collide with Rust
//! keywords: `TargetType::SelfTarget` represents C#'s `TargetType.Self`. JSON
//! payload keeps the C# spelling and is mapped via `serde(rename)`.
//!
//! All ids are stable across game versions only insofar as MegaCrit doesn't
//! rename concrete classes. If they rename `BattleTrance` to `BattleSong`,
//! re-running the extractor will produce a new id; downstream code must treat
//! ids as opaque keys.
//!
//! The table is parsed once on first access via `LazyLock`.

use serde::Deserialize;
use std::collections::HashMap;
use std::sync::LazyLock;

/// Single concrete CardModel subclass — pure data.
#[derive(Clone, Debug, Deserialize)]
pub struct CardData {
    /// Class-name id, e.g. "BattleTrance", "DefendIronclad". Used as the
    /// canonical key.
    pub id: String,
    /// CardPool subclass that owns this card (e.g., "Ironclad", "Silent",
    /// "Defect", "Regent", "Necrobinder", "Colorless", "Curse", "Status",
    /// "Token", "Event", "Quest", "Deprecated"). Mock cards are excluded.
    pub pool: String,
    /// `CanonicalEnergyCost` from the C# ctor. Some specials use sentinel
    /// values: `-1` for unplayable status cards; `0` paired with
    /// `has_energy_cost_x = true` for X-cost cards (Whirlwind).
    pub energy_cost: i32,
    pub card_type: CardType,
    pub rarity: CardRarity,
    pub target_type: TargetType,
    /// Whether the card appears in the in-game card library UI (most cards
    /// are `true`; specials like Quest cards may be hidden).
    pub show_in_library: bool,
    /// True for X-cost cards. Their `energy_cost` is the "fallback" canonical
    /// (always 0 in practice); the actual cost is resolved per-play.
    pub has_energy_cost_x: bool,
    /// Max upgrade level. 0 = unupgradable (e.g., most curses/statuses).
    /// 1 = standard single upgrade. Higher = unlimited-ish (rare; e.g.,
    /// StS1's Searing Blow had no cap).
    pub max_upgrade_level: i32,
    /// `base.EnergyCost.UpgradeBy(N)` in OnUpgrade — change to the card's
    /// base energy cost on upgrade. 0 = no change (most cards). Common
    /// values are -1 ("Costs 1 less when upgraded") and -2 (BansheesCry).
    #[serde(default)]
    pub energy_cost_upgrade_delta: i32,
    /// `CanonicalTags` set. Captured names like "Strike", "Defend".
    #[serde(default)]
    pub tags: Vec<String>,
    /// `CanonicalVars`: the base values for damage / block / cards / power
    /// stacks / etc. Order matches the C# source.
    #[serde(default)]
    pub canonical_vars: Vec<CardVar>,
    /// `OnUpgrade` body: one entry per `UpgradeValueBy(delta)` call.
    /// `var_kind` matches either a CardVar's `kind`, its `generic`, or its
    /// `key`, depending on which indexer the C# code uses.
    #[serde(default)]
    pub upgrade_deltas: Vec<UpgradeDelta>,
}

#[derive(Clone, Debug, Deserialize)]
pub struct CardVar {
    /// Var class base name, e.g. "Damage", "Block", "Cards", "Power",
    /// "Dynamic", "ExtraDamage", "CalculationBase", "CalculatedDamage", etc.
    pub kind: String,
    /// Generic type parameter, e.g. "StrengthPower" for `PowerVar<StrengthPower>`.
    #[serde(default)]
    pub generic: Option<String>,
    /// String key for `DynamicVar("Key", value)`. Used by
    /// `base.DynamicVars["Key"]` upgrade dispatch.
    #[serde(default)]
    pub key: Option<String>,
    /// Canonical numeric value. `None` for vars that don't take a literal
    /// (e.g., `CalculatedDamageVar(ValueProp.Move)` with a runtime lambda).
    #[serde(default)]
    pub base_value: Option<f64>,
    /// `ValueProp.X` arg, e.g. "Move". Present on damage/block/heal vars
    /// that participate in StS2's value-prop pipeline.
    #[serde(default)]
    pub value_prop: Option<String>,
}

#[derive(Clone, Debug, Deserialize)]
pub struct UpgradeDelta {
    /// Matches one of `CardVar::kind`, `CardVar::generic`, or `CardVar::key`,
    /// depending on which indexer the C# code uses in `OnUpgrade`.
    pub var_kind: String,
    pub delta: f64,
}

/// `CardType` enum. Names match the C# enum exactly.
#[derive(Copy, Clone, Debug, Eq, PartialEq, Deserialize)]
pub enum CardType {
    None,
    Attack,
    Skill,
    Power,
    Status,
    Curse,
    Quest,
}

/// `CardRarity` enum. Names match the C# enum exactly.
#[derive(Copy, Clone, Debug, Eq, PartialEq, Deserialize)]
pub enum CardRarity {
    None,
    Basic,
    Common,
    Uncommon,
    Rare,
    Ancient,
    Event,
    Token,
    Status,
    Curse,
    Quest,
}

/// `TargetType` enum. C# `TargetType.Self` is renamed to `SelfTarget` here
/// to avoid colliding with Rust's `Self` keyword; JSON keeps the C# spelling.
#[derive(Copy, Clone, Debug, Eq, PartialEq, Deserialize)]
pub enum TargetType {
    None,
    #[serde(rename = "Self")]
    SelfTarget,
    AnyEnemy,
    AllEnemies,
    RandomEnemy,
    AnyPlayer,
    AnyAlly,
    AllAllies,
    TargetedNoCreature,
    Osty,
}

const CARDS_JSON: &str = include_str!("../data/cards.json");

/// Parsed card table, in deterministic id-sorted order.
pub static ALL_CARDS: LazyLock<Vec<CardData>> = LazyLock::new(|| {
    let mut cards: Vec<CardData> =
        serde_json::from_str(CARDS_JSON).expect("cards.json parse failed");
    cards.sort_by(|a, b| a.id.cmp(&b.id));
    cards
});

/// Lookup by id (class-name).
pub static CARD_INDEX: LazyLock<HashMap<&'static str, &'static CardData>> = LazyLock::new(|| {
    ALL_CARDS
        .iter()
        .map(|c| (c.id.as_str(), c))
        .collect()
});

pub fn by_id(id: &str) -> Option<&'static CardData> {
    CARD_INDEX.get(id).copied()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    /// The number of game cards (mocks excluded). If this changes, a game
    /// patch shipped — re-run `cargo run -p extract-cards` and update this
    /// constant deliberately.
    const EXPECTED_CARD_COUNT: usize = 577;

    #[test]
    fn card_count_matches_expected() {
        assert_eq!(ALL_CARDS.len(), EXPECTED_CARD_COUNT);
    }

    #[test]
    fn ids_are_unique() {
        let mut seen: HashSet<&str> = HashSet::new();
        for card in ALL_CARDS.iter() {
            assert!(
                seen.insert(card.id.as_str()),
                "duplicate card id: {}",
                card.id
            );
        }
    }

    #[test]
    fn every_pool_is_known() {
        let known: HashSet<&str> = [
            "Ironclad",
            "Silent",
            "Defect",
            "Regent",
            "Necrobinder",
            "Colorless",
            "Curse",
            "Status",
            "Token",
            "Event",
            "Quest",
            "Deprecated",
        ]
        .iter()
        .copied()
        .collect();
        for card in ALL_CARDS.iter() {
            assert!(
                known.contains(card.pool.as_str()),
                "unknown pool for {}: {}",
                card.id,
                card.pool
            );
        }
    }

    #[test]
    fn pool_distribution_includes_all_five_characters() {
        // The five player characters each ship with some cards. If any one
        // is empty, something dropped during extraction.
        for ch in ["Ironclad", "Silent", "Defect", "Regent", "Necrobinder"] {
            let count = ALL_CARDS.iter().filter(|c| c.pool == ch).count();
            assert!(count > 0, "pool {} is empty", ch);
        }
    }

    #[test]
    fn basics_have_known_signatures() {
        // Lock in a few canonical reads as regression tests against parser
        // drift. Values match the v0.103.2 decompile.
        let strike = by_id("StrikeIronclad").expect("StrikeIronclad present");
        assert_eq!(strike.energy_cost, 1);
        assert_eq!(strike.card_type, CardType::Attack);
        assert_eq!(strike.rarity, CardRarity::Basic);
        assert_eq!(strike.target_type, TargetType::AnyEnemy);
        assert_eq!(strike.canonical_vars[0].kind, "Damage");
        assert_eq!(strike.canonical_vars[0].base_value, Some(6.0));

        let defend = by_id("DefendIronclad").expect("DefendIronclad present");
        assert_eq!(defend.energy_cost, 1);
        assert_eq!(defend.target_type, TargetType::SelfTarget);
        assert_eq!(defend.canonical_vars[0].kind, "Block");
        assert_eq!(defend.canonical_vars[0].base_value, Some(5.0));

        // Whirlwind: X-cost attack, 5 damage hits per energy spent.
        let ww = by_id("Whirlwind").expect("Whirlwind present");
        assert!(ww.has_energy_cost_x);
        assert_eq!(ww.energy_cost, 0);

        // Wound: unplayable status, not upgradable.
        let wound = by_id("Wound").expect("Wound present");
        assert_eq!(wound.card_type, CardType::Status);
        assert_eq!(wound.rarity, CardRarity::Status);
        assert_eq!(wound.max_upgrade_level, 0);

        // PowerVar<T>: Inflame applies StrengthPower 2 → upgrade adds 1.
        let inflame = by_id("Inflame").expect("Inflame present");
        assert_eq!(inflame.canonical_vars[0].kind, "Power");
        assert_eq!(
            inflame.canonical_vars[0].generic.as_deref(),
            Some("StrengthPower")
        );
        assert_eq!(inflame.upgrade_deltas[0].var_kind, "StrengthPower");
        assert_eq!(inflame.upgrade_deltas[0].delta, 1.0);

        // DynamicVar with string key: Accelerant.
        let acc = by_id("Accelerant").expect("Accelerant present");
        assert_eq!(acc.canonical_vars[0].kind, "Dynamic");
        assert_eq!(acc.canonical_vars[0].key.as_deref(), Some("Accelerant"));
        assert_eq!(acc.canonical_vars[0].base_value, Some(1.0));
    }

    /// Every upgrade delta should reference a var that exists on the card.
    /// Resolution: var_kind matches CardVar::kind, ::generic, ::key, OR the
    /// "stripped" form of ::generic — for PowerVar<DexterityPower>, the C#
    /// dot-accessor form is `base.DynamicVars.Dexterity` (suffix "Power"
    /// stripped from the type name).
    #[test]
    fn upgrade_deltas_reference_known_vars() {
        for card in ALL_CARDS.iter() {
            for delta in &card.upgrade_deltas {
                let found = card.canonical_vars.iter().any(|v| {
                    if v.kind == delta.var_kind { return true; }
                    if v.key.as_deref() == Some(delta.var_kind.as_str()) {
                        return true;
                    }
                    if let Some(g) = v.generic.as_deref() {
                        if g == delta.var_kind { return true; }
                        // Power-suffix-strip alias.
                        if let Some(stripped) = g.strip_suffix("Power") {
                            if stripped == delta.var_kind { return true; }
                        }
                    }
                    false
                });
                assert!(
                    found,
                    "card {}: upgrade delta refers to unknown var {} (canonical_vars={:?})",
                    card.id, delta.var_kind, card.canonical_vars
                );
            }
        }
    }

    /// max_upgrade_level == 0 cards must have no upgrade deltas.
    #[test]
    fn unupgradable_cards_have_no_deltas() {
        for card in ALL_CARDS.iter() {
            if card.max_upgrade_level == 0 {
                assert!(
                    card.upgrade_deltas.is_empty(),
                    "card {} is not upgradable but has deltas",
                    card.id
                );
            }
        }
    }

    /// Energy cost sanity. -1 is allowed (unplayable status); most cards
    /// fall in 0..=5; BansheesCry costs 9 (high-baseline archetype that
    /// reduces in play). 15 is a generous upper bound that catches obvious
    /// parser miscounts (e.g., reading "3" as "300") without flagging the
    /// game's actual outliers.
    #[test]
    fn energy_cost_is_in_sane_range() {
        for card in ALL_CARDS.iter() {
            assert!(
                (-1..=15).contains(&card.energy_cost),
                "card {} has weird energy_cost {}",
                card.id,
                card.energy_cost
            );
        }
    }
}
