//! Power (status effect) data table.
//!
//! 243 concrete `PowerModel` subclasses from the StS2 decompile, loaded from
//! `data/powers.json` (regenerated by `cargo run -p extract-powers`).
//!
//! Powers are simpler than relics: no pool (any source can apply any power)
//! and no upgrade. Mandatory data is `Type` (Buff/Debuff) and `StackType`
//! (Counter/Single); `CanonicalVars` is optional.
//!
//! Behavior virtuals (`AfterSideTurnStart`, `ModifyDamageAdditive`,
//! `ModifyDamageMultiplicative`, ...) are deferred.

use serde::Deserialize;
use std::collections::HashMap;
use std::sync::LazyLock;

#[derive(Clone, Debug, Deserialize)]
pub struct PowerData {
    /// Class-name id, e.g. "StrengthPower", "PoisonPower".
    pub id: String,
    pub power_type: PowerType,
    pub stack_type: PowerStackType,
    /// True if the stack count can go below zero (Strength is the canonical
    /// example — Weak can drive it negative). Defaults to false.
    #[serde(default)]
    pub allow_negative: bool,
    #[serde(default)]
    pub canonical_vars: Vec<PowerVar>,
}

#[derive(Clone, Debug, Deserialize)]
pub struct PowerVar {
    pub kind: String,
    #[serde(default)]
    pub generic: Option<String>,
    #[serde(default)]
    pub key: Option<String>,
    #[serde(default)]
    pub base_value: Option<f64>,
    #[serde(default)]
    pub value_prop: Option<String>,
}

/// `PowerType` enum. Names match the C# enum exactly.
#[derive(Copy, Clone, Debug, Eq, PartialEq, Deserialize)]
pub enum PowerType {
    None,
    Buff,
    Debuff,
}

/// `PowerStackType` enum. Names match the C# enum exactly.
#[derive(Copy, Clone, Debug, Eq, PartialEq, Deserialize)]
pub enum PowerStackType {
    None,
    /// Stack count accumulates and decrements per-tick (Strength, Poison,
    /// Vulnerable).
    Counter,
    /// Power is either present or not — no count (Barricade, Berserk-like).
    Single,
}

const POWERS_JSON: &str = include_str!("../data/powers.json");

pub static ALL_POWERS: LazyLock<Vec<PowerData>> = LazyLock::new(|| {
    let mut powers: Vec<PowerData> =
        serde_json::from_str(POWERS_JSON).expect("powers.json parse failed");
    powers.sort_by(|a, b| a.id.cmp(&b.id));
    powers
});

pub static POWER_INDEX: LazyLock<HashMap<&'static str, &'static PowerData>> =
    LazyLock::new(|| ALL_POWERS.iter().map(|p| (p.id.as_str(), p)).collect());

pub fn by_id(id: &str) -> Option<&'static PowerData> {
    POWER_INDEX.get(id).copied()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    /// 243 = the count of Models/Powers/*.cs files that derive from
    /// PowerModel. If this changes, a game patch shipped — re-run
    /// `cargo run -p extract-powers` and update deliberately.
    const EXPECTED_POWER_COUNT: usize = 243;

    #[test]
    fn power_count_matches_expected() {
        assert_eq!(ALL_POWERS.len(), EXPECTED_POWER_COUNT);
    }

    #[test]
    fn ids_are_unique() {
        let mut seen: HashSet<&str> = HashSet::new();
        for p in ALL_POWERS.iter() {
            assert!(seen.insert(p.id.as_str()), "duplicate power id: {}", p.id);
        }
    }

    #[test]
    fn every_power_has_a_real_type() {
        // `None` is a sentinel — no real power should leave Type unset.
        for p in ALL_POWERS.iter() {
            assert_ne!(p.power_type, PowerType::None, "power {} has Type=None", p.id);
        }
    }

    #[test]
    fn buff_and_debuff_both_populated() {
        let buffs = ALL_POWERS
            .iter()
            .filter(|p| p.power_type == PowerType::Buff)
            .count();
        let debuffs = ALL_POWERS
            .iter()
            .filter(|p| p.power_type == PowerType::Debuff)
            .count();
        assert!(buffs > 50, "suspiciously few buffs: {}", buffs);
        assert!(debuffs > 20, "suspiciously few debuffs: {}", debuffs);
        assert_eq!(buffs + debuffs, ALL_POWERS.len());
    }

    #[test]
    fn basics_have_known_signatures() {
        // Regression locks against parser drift.
        let str_pow = by_id("StrengthPower").expect("StrengthPower present");
        assert_eq!(str_pow.power_type, PowerType::Buff);
        assert_eq!(str_pow.stack_type, PowerStackType::Counter);
        assert!(str_pow.allow_negative);

        let poison = by_id("PoisonPower").expect("PoisonPower present");
        assert_eq!(poison.power_type, PowerType::Debuff);
        assert_eq!(poison.stack_type, PowerStackType::Counter);
        assert!(!poison.allow_negative);

        // Vulnerable: keyed DynamicVar with DamageIncrease 1.5.
        let vuln = by_id("VulnerablePower").expect("VulnerablePower present");
        assert_eq!(vuln.power_type, PowerType::Debuff);
        assert_eq!(vuln.stack_type, PowerStackType::Counter);
        assert_eq!(vuln.canonical_vars.len(), 1);
        assert_eq!(vuln.canonical_vars[0].kind, "Dynamic");
        assert_eq!(vuln.canonical_vars[0].key.as_deref(), Some("DamageIncrease"));
        assert_eq!(vuln.canonical_vars[0].base_value, Some(1.5));
    }
}
