//! Relic data table.
//!
//! Pure data — no behavior. 294 concrete `RelicModel` subclasses from the
//! StS2 decompile, loaded from `data/relics.json` (regenerated by
//! `cargo run -p extract-relics`).
//!
//! Relics are structurally simpler than cards: no positional ctor args (the
//! base ctor is parameterless), no upgrade mechanics. The only mandatory
//! data is `Rarity`; `CanonicalVars` holds magic numbers (counter values,
//! one-shot block/heal amounts, etc.).
//!
//! Behavior (`BeforeCombatStart`, `AfterCombatVictory`, `OnTrigger`, ...)
//! lives in a later port.

use serde::Deserialize;
use std::collections::HashMap;
use std::sync::LazyLock;

/// Single concrete RelicModel subclass — pure data.
#[derive(Clone, Debug, Deserialize)]
pub struct RelicData {
    /// Class-name id, e.g. "BurningBlood", "Anchor".
    pub id: String,
    /// Pools that list this relic in their `GenerateAllRelics()`. Most relics
    /// belong to one (Ironclad/Silent/Defect/Regent/Necrobinder for
    /// character-specific starters, Shared for cross-character commons,
    /// Event for event rewards). Some appear in multiple — LastingCandy is
    /// in both Event and Shared.
    pub pools: Vec<String>,
    pub rarity: RelicRarity,
    /// `CanonicalVars`: counters/magic numbers used by relic effects.
    /// Same shape as card vars (see `card::CardVar`).
    #[serde(default)]
    pub canonical_vars: Vec<RelicVar>,
}

#[derive(Clone, Debug, Deserialize)]
pub struct RelicVar {
    pub kind: String,
    #[serde(default)]
    pub generic: Option<String>,
    #[serde(default)]
    pub key: Option<String>,
    #[serde(default)]
    pub base_value: Option<f64>,
    #[serde(default)]
    pub value_prop: Option<String>,
}

/// `RelicRarity` enum. Names match the C# enum exactly.
#[derive(Copy, Clone, Debug, Eq, PartialEq, Deserialize)]
pub enum RelicRarity {
    None,
    Starter,
    Common,
    Uncommon,
    Rare,
    Shop,
    Event,
    Ancient,
}

const RELICS_JSON: &str = include_str!("../data/relics.json");

pub static ALL_RELICS: LazyLock<Vec<RelicData>> = LazyLock::new(|| {
    let mut relics: Vec<RelicData> =
        serde_json::from_str(RELICS_JSON).expect("relics.json parse failed");
    relics.sort_by(|a, b| a.id.cmp(&b.id));
    relics
});

pub static RELIC_INDEX: LazyLock<HashMap<&'static str, &'static RelicData>> =
    LazyLock::new(|| {
        ALL_RELICS
            .iter()
            .map(|r| (r.id.as_str(), r))
            .collect()
    });

pub fn by_id(id: &str) -> Option<&'static RelicData> {
    RELIC_INDEX.get(id).copied()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    /// 294 = 295 files on disk minus VakuuCardSelector (an ICardSelector
    /// utility that lives in the Relics dir but isn't a RelicModel). If
    /// this changes, a game patch shipped — re-run the extractor and
    /// update deliberately.
    const EXPECTED_RELIC_COUNT: usize = 294;

    #[test]
    fn relic_count_matches_expected() {
        assert_eq!(ALL_RELICS.len(), EXPECTED_RELIC_COUNT);
    }

    #[test]
    fn ids_are_unique() {
        let mut seen: HashSet<&str> = HashSet::new();
        for r in ALL_RELICS.iter() {
            assert!(seen.insert(r.id.as_str()), "duplicate relic id: {}", r.id);
        }
    }

    #[test]
    fn every_relic_has_at_least_one_pool() {
        for r in ALL_RELICS.iter() {
            assert!(!r.pools.is_empty(), "relic {} has no pool", r.id);
        }
    }

    #[test]
    fn every_pool_is_known() {
        let known: HashSet<&str> = [
            "Ironclad",
            "Silent",
            "Defect",
            "Regent",
            "Necrobinder",
            "Shared",
            "Event",
            "Deprecated",
            "Fallback",
        ]
        .iter()
        .copied()
        .collect();
        for r in ALL_RELICS.iter() {
            for p in &r.pools {
                assert!(
                    known.contains(p.as_str()),
                    "unknown pool for {}: {}",
                    r.id,
                    p
                );
            }
        }
    }

    /// Every character should have exactly one Starter relic in their pool.
    /// (Ironclad → BurningBlood, Silent → RingOfSnake, Defect → CrackedCore,
    /// etc. — exact starter names vary, but each character has 1.)
    #[test]
    fn each_character_pool_has_one_starter() {
        for ch in ["Ironclad", "Silent", "Defect", "Regent", "Necrobinder"] {
            let count = ALL_RELICS
                .iter()
                .filter(|r| {
                    r.pools.iter().any(|p| p == ch) && r.rarity == RelicRarity::Starter
                })
                .count();
            assert_eq!(
                count, 1,
                "expected exactly 1 Starter relic in pool {}, got {}",
                ch, count
            );
        }
    }

    #[test]
    fn basics_have_known_signatures() {
        // Regression locks against parser drift.
        let bb = by_id("BurningBlood").expect("BurningBlood present");
        assert_eq!(bb.rarity, RelicRarity::Starter);
        assert!(bb.pools.contains(&"Ironclad".to_string()));
        assert_eq!(bb.canonical_vars[0].kind, "Heal");
        assert_eq!(bb.canonical_vars[0].base_value, Some(6.0));

        let anchor = by_id("Anchor").expect("Anchor present");
        assert_eq!(anchor.rarity, RelicRarity::Common);
        assert_eq!(anchor.canonical_vars[0].kind, "Block");
        assert_eq!(anchor.canonical_vars[0].base_value, Some(10.0));
        assert_eq!(anchor.canonical_vars[0].value_prop.as_deref(), Some("Unpowered"));

        let cc = by_id("CrackedCore").expect("CrackedCore present");
        assert_eq!(cc.rarity, RelicRarity::Starter);
        assert!(cc.pools.contains(&"Defect".to_string()));
        assert_eq!(cc.canonical_vars[0].kind, "Dynamic");
        assert_eq!(cc.canonical_vars[0].key.as_deref(), Some("Lightning"));
        assert_eq!(cc.canonical_vars[0].base_value, Some(1.0));

        // Multi-pool relic.
        let lc = by_id("LastingCandy").expect("LastingCandy present");
        assert!(lc.pools.contains(&"Shared".to_string()));
        assert!(lc.pools.contains(&"Event".to_string()));
    }
}
