"""Inject autogen.py output into effects.rs::card_effects()."""
import os
import sys

here = os.path.dirname(__file__)
repo = os.path.dirname(os.path.dirname(here))

# Read the autogen output file (regenerate with `python autogen.py > autogen_out.rs`).
with open(os.path.join(here, 'autogen_out.rs'), 'rb') as f:
    inject_raw = f.read().decode('utf-8', errors='replace')

# Keep only match-arm lines and SKIP comments (drop the autogen header).
keep = []
for line in inject_raw.splitlines(True):
    s = line.lstrip()
    if s.startswith('"') or (s.startswith('//') and 'SKIP' in s):
        keep.append(line)
inject_text = ''.join(keep)

effects_path = os.path.join(repo, 'crates', 'sts2-sim', 'src', 'effects.rs')
with open(effects_path, 'r', encoding='utf-8') as f:
    src = f.read()

# Strip any previously-injected autogen block so re-running is idempotent.
import re as _re
prev_pattern = _re.compile(
    r'\n        // ===== Auto-generated bulk card port \(553 cards\) =====.*?(?=        _ => None,)',
    _re.S,
)
src = prev_pattern.sub('', src)

marker = '        _ => None,'
idx = src.find(marker)
if idx < 0:
    print('ERROR: marker not found', file=sys.stderr)
    sys.exit(1)

prelude = (
    '\n        // ===== Auto-generated bulk card port (553 cards) =====\n'
    '        // Generated by tools/merge_card_ports/autogen.py from cards.json.\n'
    '        // ~328 encoded by shape-match; ~225 skipped (need primitive that\n'
    '        // is missing, stub-only, or have a shape the auto-encoder did\n'
    '        // not recognize). SKIP comments below name each.\n\n'
)

new_src = src[:idx] + prelude + inject_text + '\n' + src[idx:]

with open(effects_path, 'w', encoding='utf-8') as f:
    f.write(new_src)

print(f'OK: injected {len(inject_text)} chars; {inject_text.count(chr(34))//2} arms')
